/* Generated static Chinese localization for pages sharing the full English structure. */
const zhTranslations = {
  "4869 — Local Encrypted Folder Vault for macOS": "4869 — 适用于 macOS 的本地加密文件夹库",
  "Features": "特征",
  "Security": "安全",
  "How It Works": "工作原理",
  "Decoy &amp; Recovery": "诱饵与恢复",
  "FAQ": "常问问题",
  "Privacy": "隐私",
  "Support": "支持",
  "Now available for macOS": "现已适用于 macOS",
  "Your files.": "你的文件。",
  "Protected locally.": "本地保护。",
  "4869 turns any folder on your Mac into a fortified encrypted vault.\n                No cloud. No servers. No accounts. Just uncompromising cryptography\n                that keeps your data yours.": "4869 将 Mac 上的任何文件夹变成强化的加密保险库。\n                没有云。没有服务器。没有账户。不妥协的密码学\n                让您的数据归您所有。",
  "Download for Mac": "下载 macOS 版",
  "Explore the Cryptography →": "探索密码学 →",
  "0-bit": "0位",
  "Encryption": "加密",
  "0 MB": "0MB",
  "Memory-Hard KDF": "硬内存 KDF",
  "Servers Required": "所需服务器",
  "PQ-Safe": "PQ-安全",
  "Post-Quantum Ready": "后量子准备就绪",
  "Built for people who take privacy seriously.": "专为重视隐私的人们而打造。",
  "Every feature in 4869 exists to give you absolute control over your data.\n                    From the cryptography to the user experience, nothing is compromised.": "4869 中的每一项功能都是为了让您对数据拥有绝对的控制权。\n                    从密码学到​​用户体验，一切都不会受到影响。",
  "Double-Layer Encryption": "双层加密",
  "Every file is encrypted with AES-256-GCM inside ChaCha20-Poly1305. Even if one cipher is ever broken, your data remains protected by the other — defense in depth at the protocol level.": "每个文件都在 ChaCha20-Poly1305 内使用 AES-256-GCM 进行加密。即使一个密码被破解，您的数据仍然受到另一个密码的保护——协议级别的深度防御。",
  "Memory-Hard Key Derivation": "内存硬密钥派生",
  "Your password is stretched through scrypt (RFC 7914) with N=131,072, forcing 128 MB of RAM per attempt. GPU and ASIC brute-force attacks become economically prohibitive.": "您的密码通过 scrypt (RFC 7914) 进行扩展，N=131,072，每次尝试强制使用 128 MB RAM。 GPU 和 ASIC 暴力攻击在经济上变得令人望而却步。",
  "Plausible Deniability": "合理否认",
  "Set up a decoy password that unlocks harmless placeholder files. An attacker cannot determine from the vault metadata whether the decoy or the real data was revealed.": "设置一个诱饵密码来解锁无害的占位符文件。攻击者无法从保险库元数据中确定是否泄露了诱饵数据或真实数据。",
  "Post-Quantum Recovery": "后量子恢复",
  "Optional recovery key powered by XWing-MLKEM768-X25519 hybrid KEM. If you forget your password, your data survives — and it's ready for the quantum computing era.": "由 XWing-MLKEM768-X25519 混合 KEM 提供支持的可选恢复密钥。如果您忘记了密码，您的数据仍然存在，并且为量子计算时代做好了准备。",
  "Secure Deletion": "安全删除",
  "Originals are overwritten with random data, truncated, then unlinked. Effectiveness depends on the storage hardware and filesystem; SSDs and copy-on-write filesystems cannot guarantee complete erasure.": "原始数据被随机数据覆盖、截断，然后取消链接。有效性取决于存储硬件和文件系统； SSD 和写时复制文件系统不能保证完全擦除。",
  "Native Finder Integration": "原生 Finder 集成",
  "Encrypted folders become  packages that open directly in 4869. Double-click to unlock, just like opening any document on your Mac.": "加密的文件夹成为直接在4869中打开的包，双击即可解锁，就像打开Mac上的任何文档一样。",
  "Temporary Viewing Sessions": "临时观看时段",
  "Peek at your files without fully unlocking. Temporary sessions remove decrypted copies after 1–30 minutes, during orderly app termination, or on the next launch after an interruption.": "无需完全解锁即可查看您的文件。临时会话会在 1-30 分钟后、有序应用程序终止期间或中断后下次启动时删除解密的副本。",
  "100% Offline": "100%离线",
  "No internet connection required. No telemetry, analytics, accounts, or network requests are implemented in the app.": "无需互联网连接。应用程序中未实现任何遥测、分析、帐户或网络请求。",
  "Cryptographic Self-Test": "密码自检",
  "On every launch, 4869 verifies SHA-256, AES-GCM, ChaCha20-Poly1305, and scrypt against known test vectors. If anything fails, the app refuses to operate.": "每次启动时，4869 都会根据已知的测试向量验证 SHA-256、AES-GCM、ChaCha20-Poly1305 和 scrypt。如果出现任何问题，应用程序将拒绝运行。",
  "Security Architecture": "安全架构",
  "Cryptography you can audit.": "您可以审核密码学。",
  "4869 uses only well-established, peer-reviewed algorithms from Apple's\n                    CryptoKit and CommonCrypto frameworks. No custom crypto. No proprietary\n                    algorithms. No obfuscation masquerading as security.": "4869 仅使用 Apple 的成熟且经过同行评审的算法\n                    CryptoKit 和 CommonCrypto 框架。没有自定义加密货币。无专有\n                    算法。没有伪装成安全性的混淆。",
  "Encryption Pipeline (Layer by Layer)": "加密管道（逐层）",
  "Password Validation": "密码验证",
  "Minimum 16 characters, entropy estimation ≥ 80 bits. Rejects common, repeated, and sequential passwords.": "最少 16 个字符，熵估计 ≥ 80 位。拒绝常见、重复和连续的密码。",
  "PasswordPolicy": "密码策略",
  "scrypt Key Derivation (RFC 7914)": "scrypt 密钥派生 (RFC 7914)",
  "N=131,072 · r=8 · p=1 · dkLen=32 bytes. Forces ~128 MB RAM per derivation attempt. With application pepper mixed into the salt.": "N=131,072 · r=8 · p=1 · dkLen=32 字节。每次派生尝试强制使用 ~128 MB RAM。用胡椒粉拌入盐中。",
  "Memory-Hard": "记忆困难",
  "Master Key Generation": "主密钥生成",
  "64-byte cryptographically random master key generated via . Never derived from or stored alongside the password.": "通过 生成的 64 字节加密随机主密钥。切勿从密码中派生或与密码一起存储。",
  "CSPRNG": "CSPRNG",
  "Key Wrapping (AES-256-GCM)": "密钥包装 (AES-256-GCM)",
  "Master key sealed with the scrypt-derived key using AES-256-GCM authenticated encryption. Includes a verification check value.": "使用 AES-256-GCM 验证加密，用 scrypt 派生密钥密封主密钥。包括验证检查值。",
  "AEAD": "AEAD",
  "Per-File Key Separation (HKDF-SHA512)": "每个文件密钥分离 (HKDF-SHA512)",
  "Each file gets a unique sub-key derived via HKDF-SHA512 with a purpose-specific info string. Compromise of one key cannot cascade.": "每个文件都有一个通过 HKDF-SHA512 派生的唯一子密钥，其中包含特定用途的信息字符串。一键泄露无法级联。",
  "Key Isolation": "按键隔离",
  "Chunked Double-Layer Encryption": "分块双层加密",
  "Files split into 4 MB chunks. Each chunk sealed with AES-256-GCM (inner), then wrapped in ChaCha20-Poly1305 (outer). Per-chunk AAD binds position and path.": "文件分割成 4 MB 的块。每个块都用 AES-256-GCM（内部）密封，然后用 ChaCha20-Poly1305（外部）包裹。每块 AAD 绑定位置和路径。",
  "Dual AEAD": "双AEAD",
  "SHA-256 Integrity Verification": "SHA-256 完整性验证",
  "Every file's plaintext hash is stored inside the encrypted manifest. Decryption fails if even a single byte is altered.": "每个文件的明文哈希都存储在加密清单中。即使改变一个字节，解密也会失败。",
  "Tamper-Proof": "防篡改",
  "Post-Quantum Recovery (Optional)": "后量子恢复（可选）",
  "XWing-MLKEM768-X25519 hybrid KEM wraps the master key. AES-256-GCM sealed envelope with HKDF-SHA512 derived wrapping key. Resistant to Shor's algorithm.": "XWing-MLKEM768-X25519 混合 KEM 包装主密钥。 AES-256-GCM 密封信封，带有 HKDF-SHA512 派生的包装密钥。抵抗 Shor 算法。",
  "Quantum-Safe": "量子安全",
  "Metadata Concealment": "元数据隐藏",
  "File names, directory structure, file counts, and total sizes are encrypted inside the manifest. An attacker sees only opaque ciphertext.": "文件名、目录结构、文件计数和总大小在清单内加密。攻击者只能看到不透明的密文。",
  "Zero Leakage": "零泄漏",
  "Runtime Hardening": "运行时强化",
  "Core dumps disabled ().  for owner-only files. Mutable key buffers are zeroed on a best-effort basis.": "核心转储已禁用 ()。  对于仅限所有者的文件。可变密钥缓冲区会尽力归零。",
  "Hardened": "硬化",
  "Technical Specifications": "技术规格",
  "Encryption Algorithm": "加密算法",
  "AES-256-GCM + ChaCha20-Poly1305 (double-layer AEAD)": "AES-256-GCM + ChaCha20-Poly1305（双层AEAD）",
  "Key Derivation": "密钥派生",
  "scrypt (RFC 7914)": "scrypt（RFC 7914）",
  "scrypt Parameters": "scrypt 参数",
  "N = 131,072 (2¹⁷) · r = 8 · p = 1": "N = 131,072 (2^⁷) · r = 8 · p = 1",
  "Memory per Derivation": "每个推导的内存",
  "~128 MB": "〜128MB",
  "Master Key Size": "主钥匙尺寸",
  "512 bits (64 bytes), CSPRNG-generated": "512 位（64 字节），CSPRNG 生成",
  "Sub-Key Derivation": "子密钥派生",
  "HKDF-SHA512 with domain-separated info strings": "具有域分隔信息字符串的 HKDF-SHA512",
  "Salt Size": "盐尺寸",
  "256 bits (32 bytes) per vault, CSPRNG-generated": "每个库 256 位（32 字节），CSPRNG 生成",
  "Chunk Size": "块大小",
  "4 MB (4,194,304 bytes)": "4 MB（4,194,304 字节）",
  "Integrity Hash": "完整性哈希",
  "SHA-256 (stored in encrypted manifest)": "SHA-256（存储在加密清单中）",
  "XWing-MLKEM768-X25519-HKDFSHA512-AES256GCM": "XWing-MLKEM768-X25519-HKDFSHA512-AES256GCM",
  "Legacy PBKDF2 (v1 vaults)": "旧版 PBKDF2（v1 保险库）",
  "PBKDF2-HMAC-SHA512, 1,200,000 iterations": "PBKDF2-HMAC-SHA512，1,200,000 次迭代",
  "Minimum Password Length": "最短密码长度",
  "16 characters, ≥ 80 bits estimated entropy": "16 个字符，≥ 80 位估计熵",
  "Random Number Generator": "随机数生成器",
  "SecRandomCopyBytes (macOS cryptographically secure random generator)": "SecRandomCopyBytes（macOS 加密安全随机生成器）",
  "Format Version": "格式版本",
  "v4 (chunked RFC 7914 scrypt + dual AEAD + HKDF-SHA512)": "v4（分块 RFC 7914 scrypt + 双 AEAD + HKDF-SHA512）",
  "Platform": "平台",
  "macOS 15.6+ (post-quantum recovery requires macOS 26+)": "macOS 15.6+（后量子恢复需要 macOS 26+）",
  "Data Collection": "数据收集",
  "None — zero network access, zero telemetry": "无 — 零网络访问、零遥测",
  "Lock in seconds. Unlock in seconds.": "几秒钟内锁定。几秒钟内解锁。",
  "Three steps. No accounts, no cloud, no learning curve.": "三步。没有账户，没有云，没有学习曲线。",
  "Drop a folder into 4869": "将文件夹放入 4869",
  "Drag any folder onto the app window, or use the file picker. 4869 scans every file, rejects symlinks, and counts the total to be encrypted.": "将任何文件夹拖到应用程序窗口上，或使用文件选择器。 4869 扫描每个文件，拒绝符号链接，并计算要加密的总数。",
  "Set a strong password": "设置强密码",
  "Choose a password of at least 16 characters. The built-in strength estimator helps you find the sweet spot between security and memorability. Optionally configure a decoy password for plausible deniability.": "选择至少 16 个字符的密码。内置强度估算器可帮助您找到安全性和记忆性之间的最佳平衡点。可以选择配置一个诱饵密码，以实现合理否认。",
  "4869 encrypts, verifies, and seals": "第4869章 加密、验证、封印",
  "Every file is encrypted in 4 MB chunks with dual AEAD. The entire vault is then test-decrypted and verified against SHA-256 hashes before any plaintext is removed. Only after verification are originals securely shredded.": "每个文件均使用双 AEAD 以 4 MB 块的形式进行加密。然后，在删除任何明文之前，会对整个保险库进行测试解密并根据 SHA-256 哈希值进行验证。只有在验证后，原件才会被安全安全删除。",
  "Double-click to unlock anytime": "双击即可随时解锁",
  "Your folder becomes a  package with a custom locked icon. Double-click it in Finder, enter your password, and your files are restored exactly as they were — directory structure, timestamps, everything.": "您的文件夹将成为带有自定义锁定图标的包。在 Finder 中双击它，输入密码，您的文件就会完全恢复原样 - 目录结构、时间戳等一切。",
  "What a vault looks like on disk": "磁盘上的保险库是什么样子",
  "The vault metadata () contains only what's necessary for decryption.\n                    File names, paths, counts, and sizes live inside the encrypted manifest —\n                    an attacker examining the metadata learns nothing about your data.": "保险库元数据 () 仅包含解密所需的内容。\n                    文件名、路径、计数和大小位于加密清单中 -\n                    检查元数据的攻击者不会了解您的数据。",
  "Why 4869": "为什么4869",
  "How 4869 compares to alternatives.": "4869 与替代品相比如何。",
  "Most \"encryption\" apps trust a server somewhere. 4869 trusts nothing but math.": "大多数“加密”应用程序都信任某处的服务器。 4869 除了数学什么都不相信。",
  "Capability": "能力",
  "Cloud Vault Apps": "云保险库应用程序",
  "Built-in FileVault": "内置文件库",
  "Works fully offline": "完全离线工作",
  "✓ Yes": "✓ 是",
  "✗ Requires internet": "✗ 需要互联网",
  "Per-folder encryption": "每个文件夹加密",
  "✓ Any folder": "✓ 任何文件夹",
  "✓ Selected folders": "✓ 选定的文件夹",
  "✗ Entire disk only": "✗ 仅整个磁盘",
  "Double-layer AEAD": "双层AEAD",
  "✓ AES-GCM + ChaCha20": "✓ AES-GCM + ChaCha20",
  "✗ Single algorithm": "✗ 单一算法",
  "Memory-hard KDF (scrypt)": "内存硬型 KDF (scrypt)",
  "✓ 128 MB": "✓ 128MB",
  "✗ PBKDF2 (low cost)": "✗ PBKDF2（低成本）",
  "Plausible deniability": "合理的推诿",
  "✓ Decoy passwords": "✓ 诱饵密码",
  "✗ Not available": "✗ 不可用",
  "Post-quantum recovery": "后量子恢复",
  "✓ XWing hybrid KEM": "✓ XWing 混合 KEM",
  "No servers / no account": "没有服务器/没有帐户",
  "✓ Zero infrastructure": "✓ 零基础设施",
  "✗ Server-dependent": "✗ 依赖于服务器",
  "No telemetry / analytics": "无遥测/分析",
  "✓ Zero tracking": "✓ 零跟踪",
  "✗ Often collected": "✗ 经常收藏",
  "Secure file shredding": "安全删除原始文件",
  "✓ Overwrite + unlink": "✓ 覆盖+取消链接",
  "✗ Simple delete": "✗ 简单删除",
  "✗ N/A": "✗ 不适用",
  "Crypto self-test on launch": "启动时进行加密自测试",
  "✓ SHA/AES/ChaCha/scrypt": "✓ SHA/AES/ChaCha/scrypt",
  "✗ Not performed": "✗ 未执行",
  "Advanced Protection": "高级保护",
  "Decoy passwords and recovery keys, step by step.": "诱饵密码与恢复密钥：逐步使用指南",
  "These features solve different problems. A decoy password provides a separate harmless view; a recovery key provides emergency access when the real password is unavailable.": "这些功能解决不同的问题。诱饵密码提供了一个单独的无害视图；当真实密码不可用时，恢复密钥可提供紧急访问。",
  "How to configure a decoy password": "如何配置诱饵密码",
  "Select an unlocked folder and enter your real password twice.": "选择一个未锁定的文件夹并输入两次真实密码。",
  "Expand": "扩张",
  "Enter a different decoy password of at least 16 characters. It must not match the real password.": "输入至少 16 个字符的不同诱饵密码。它必须与真实密码不匹配。",
  "Lock the folder normally. The current app creates a harmless  placeholder for the decoy view.": "正常锁定文件夹。当前的应用程序为诱饵视图创建了一个无害的占位符。",
  "If you later enter the decoy password, the vault remains a  package and reveals only the placeholder. Entering the real password restores the actual files.": "如果您稍后输入诱饵密码，保险库将保留为一个包，并且仅显示占位符。输入真实密码即可恢复实际文件。",
  "Decoy limitations": "诱饵限制",
  "The decoy is not a second backup, and it does not make the existence of encrypted data disappear. It is designed so the metadata does not directly reveal whether a decoy slot is genuine, but operational clues, backups, logs, file history, or user behavior may still reveal information.": "诱饵不是第二次备份，它不会使加密数据的存在消失。它的设计使得元数据不会直接揭示诱饵槽是否真实，但操作线索、备份、日志、文件历史记录或用户行为仍然可能泄露信息。",
  "Test both passwords before relying on the feature. Never reuse either password, and never use the decoy password as the real password for another vault.": "在依赖该功能之前测试这两个密码。切勿重复使用任一密码，也切勿使用诱饵密码作为另一个保险库的真实密码。",
  "How to generate a recovery key": "如何生成恢复密钥",
  "Use macOS 26 or later; the switch is disabled on older systems.": "使用 macOS 26 或更高版本；该开关在旧系统上被禁用。",
  "Before locking, enable": "锁定前，启用",
  "Post-Quantum Recovery Key": "后量子恢复密钥",
  "After encryption succeeds, choose a save location for the generated  document.": "加密成功后，选择生成的文档的保存位置。",
  "Store it separately from the vault—for example, on an offline encrypted drive. Do not leave the only copy next to the vault.": "将其与保险库分开存储 - 例如，存储在离线加密驱动器上。不要将唯一的副本留在保险库旁边。",
  "Keep the normal password as your primary unlock method. The recovery document is an emergency credential.": "保留普通密码作为您的主要解锁方法。恢复文件是紧急凭证。",
  "How to recover a vault": "如何恢复保险库",
  "Select the locked  vault in 4869.": "选择4869中锁定的保险库。",
  "Click": "点击",
  "Recovery Key": "恢复密钥",
  "instead of entering a password.": "而不是输入密码。",
  "Choose the matching  document.": "选择匹配的文档。",
  "4869 validates the key, decrypts the manifest, restores every file in staging, verifies hashes, and only then commits the restored folder.": "4869 验证密钥、解密清单、恢复暂存中的每个文件、验证哈希值，然后才提交恢复的文件夹。",
  "Anyone holding both the vault and its recovery key can decrypt it.": "任何持有保险库及其恢复密钥的人都可以解密它。",
  "A lost recovery key cannot be regenerated from the vault. Creating a new vault generates a different key.": "丢失的恢复密钥无法从保险库重新生成。创建新的保险库会生成不同的密钥。",
  "Questions, answered.": "常见问题解答",
  "Everything you need to know about how 4869 protects your data.": "关于 4869 如何保护您的数据，您需要了解的一切。",
  "Can I recover my files if I forget my password?": "如果忘记密码，我可以恢复我的文件吗？",
  "Without a password or recovery key, your data is mathematically unrecoverable — this is by design. However, if you enabled": "如果没有密码或恢复密钥，您的数据在数学上是无法恢复的——这是设计使然。但是，如果您启用了",
  "when encrypting, you can use the exported recovery key to unlock the vault at any time. The recovery key uses XWing-MLKEM768-X25519 hybrid key encapsulation. We strongly recommend enabling it and storing the key in a safe location.": "加密时，您可以随时使用导出的恢复密钥解锁保险库。恢复密钥采用XWing-MLKEM768-X25519混合密钥封装。我们强烈建议启用它并将密钥存储在安全的位置。",
  "Does 4869 send any data to the internet?": "4869 是否向互联网发送任何数据？",
  "No. The current version implements no servers, API calls, telemetry, crash reporting, analytics, or other network requests. You can run 4869 with your network connection disabled; its local encryption features work identically.": "否。当前版本不实现服务器、API 调用、遥测、崩溃报告、分析或其他网络请求。您可以在禁用网络连接的情况下运行 4869；其本地加密功能的工作原理相同。",
  "What happens to my original files after encryption?": "加密后我的原始文件会怎样？",
  "After every encrypted file has been verified by test-decrypting it and checking its SHA-256 hash, 4869 securely shreds the originals. Each file is overwritten with cryptographically random data, truncated to zero bytes, then unlinked from the filesystem. This makes recovery with forensic tools (TestDisk, PhotoRec, Autopsy) impractical. On SSDs with wear-leveling, no software can guarantee 100% destruction, but 4869 raises the bar as high as the hardware allows.": "通过测试解密并检查其 SHA-256 哈希值来验证每个加密文件后，4869 会安全地安全删除原始文件。每个文件都被加密随机数据覆盖，截断为零字节，然后从文件系统取消链接。这使得使用取证工具（TestDisk、PhotoRec、Autopsy）进行恢复变得不切实际。对于具有磨损均衡功能的 SSD，没有软件可以保证 100% 破坏，但 4869 将标准提高到硬件允许的最高水平。",
  "What is plausible deniability and how does the decoy work?": "什么是合理否认？诱饵密码如何工作？",
  "When you set a decoy password, 4869 creates a second, hidden encrypted \"slot\" inside the vault metadata. If you are ever coerced into revealing your password, you can provide the decoy password instead. It will unlock a separate set of harmless files (either files you designate or a default placeholder). The vault metadata is designed so that an examiner cannot determine from its structure whether the real or decoy password was used. Even when no decoy is configured, the decoy fields are filled with random data that is indistinguishable from real encrypted content.": "当您设置诱饵密码时，4869 会在保险库元数据内创建第二个隐藏的加密“槽”。如果您被迫透露密码，您可以提供诱饵密码。它将解锁一组单独的无害文件（您指定的文件或默认占位符）。保险库元数据的设计使检查者无法从其结构确定使用的是真实密码还是诱饵密码。即使没有配置诱饵，诱饵字段也会填充与真实加密内容无法区分的随机数据。",
  "Why use two encryption algorithms (AES-GCM and ChaCha20)?": "为什么使用两种加密算法（AES-GCM 和 ChaCha20）？",
  "Defense in depth. Each file chunk is first sealed with AES-256-GCM, then the result is wrapped in ChaCha20-Poly1305. Both are authenticated encryption schemes (AEAD) — they provide confidentiality and integrity simultaneously. Using two independent algorithms means that even if a catastrophic vulnerability were discovered in one cipher, the other would still protect your data. This is the same principle behind TLS 1.3's hybrid designs.": "纵深防御。每个文件块首先用 AES-256-GCM 密封，然后将结果包装在 ChaCha20-Poly1305 中。两者都是经过身份验证的加密方案（AEAD）——它们同时提供机密性和完整性。使用两种独立的算法意味着即使在一种密码中发现灾难性漏洞，另一种密码仍然可以保护您的数据。这与 TLS 1.3 混合设计背后的原理相同。",
  "Is scrypt better than PBKDF2?": "scrypt 比 PBKDF2 更好吗？",
  "For password-based encryption, yes. PBKDF2 is CPU-hard but not memory-hard — an attacker can build specialized hardware (ASICs) that compute millions of PBKDF2 attempts in parallel for very little cost. scrypt (RFC 7914) is both CPU-hard and memory-hard: each derivation attempt requires ~128 MB of RAM, which means an attacker would need to provision enormous amounts of memory to parallelize brute-force attacks. A 24 GB GPU can only run about 180 concurrent scrypt instances, making large-scale attacks economically impractical.": "对于基于密码的加密，是的。 PBKDF2 是 CPU 困难的，但不是内存困难的——攻击者可以构建专门的硬件 (ASIC)，以很少的成本并行计算数百万次 PBKDF2 尝试。 scrypt (RFC 7914) 既是 CPU 难题，又是内存难题：每次派生尝试都需要约 128 MB 的 RAM，这意味着攻击者需要提供大量内存来并行进行暴力攻击。 24 GB GPU 只能运行大约 180 个并发 scrypt 实例，使得大规模攻击在经济上不切实际。",
  "What does \"post-quantum ready\" mean?": "“后量子准备就绪”是什么意思？",
  "Traditional public-key cryptography (RSA, ECC, Diffie-Hellman) can be broken by a sufficiently powerful quantum computer using Shor's algorithm. 4869's optional recovery system uses XWing, a hybrid Key Encapsulation Mechanism that combines ML-KEM-768 (NIST's post-quantum standard, formerly CRYSTALS-Kyber) with X25519 (classical elliptic curve). This means the recovery key remains secure even if large-scale quantum computers become a reality. XWing is available starting from macOS 26.": "传统的公钥密码学（RSA、ECC、Diffie-Hellman）可以通过使用 Shor 算法的足够强大的量子计算机来破解。 4869 的可选恢复系统使用 XWing，这是一种混合密钥封装机制，结合了 ML-KEM-768（NIST 的后量子标准，以前的 CRYSTALS-Kyber）与 X25519（经典椭圆曲线）。这意味着即使大规模量子计算机成为现实，恢复密钥仍然安全。 XWing 从 macOS 26 开始可用。",
  "Can 4869 encrypt any type of file?": "4869可以加密任何类型的文件吗？",
  "4869 can encrypt any regular file — documents, photos, videos, databases, archives, source code, anything. It preserves the complete directory structure (including empty folders) and file modification timestamps. The only restriction is that symbolic links are rejected for security reasons. There is no file size limit; large files are processed in 4 MB chunks to keep memory usage flat.": "4869 可以加密任何常规文件 - 文档、照片、视频、数据库、档案、源代码等等。它保留完整的目录结构（包括空文件夹）和文件修改时间戳。唯一的限制是出于安全原因拒绝符号链接。没有文件大小限制；大文件以 4 MB 块的形式进行处理，以保持内存使用平稳。",
  "What if the app crashes during encryption?": "如果应用程序在加密期间崩溃怎么办？",
  "4869 is designed for crash safety. During encryption, all work happens in temporary directories. The original files are not touched until every encrypted chunk has been written, verified by test-decryption, and confirmed via SHA-256. Only then are originals removed. If the app crashes at any point, the temporary data is cleaned up on the next launch, and your original files remain completely intact. The app also supports a rollback mechanism that re-decrypts committed data if plaintext cleanup fails.": "4869 专为碰撞安全而设计。加密期间，所有工作都发生在临时目录中。在写入每个加密块、通过测试解密验证并通过 SHA-256 确认之前，不会触及原始文件。只有这样，原件才会被移除。如果应用程序在任何时候崩溃，临时数据将在下次启动时清除，并且您的原始文件保持完整。该应用程序还支持回滚机制，如果明文清理失败，该机制会重新解密提交的数据。",
  "Is 4869 open source?": "4869开源吗？",
  "The website, release downloads, security documentation, and issue tracker are available on": "网站、版本下载、安全文档和问题跟踪器可在",
  "GitHub": "GitHub",
  ". The cryptographic design is documented for independent review.": "。加密设计被记录下来以供独立审查。",
  "Ready to take control of your data?": "准备好掌控您的数据了吗？",
  "Download 4869 and encrypt your first folder in under a minute.": "下载 4869 并在一分钟内加密您的第一个文件夹。",
  "Get Support": "获得支持",
  "Local folder encryption for macOS. Your files stay under your control.": "适用于 macOS 的本地文件夹加密。您的文件由您掌控。",
  "Product": "产品",
  "Legal": "合法的",
  "Privacy Policy": "隐私政策",
  "Terms of Use": "使用条款",
  "Disclaimer": "免责声明",
  "License": "执照",
  "Connect": "连接",
  "Issues": "问题",
  "&copy; 2024–2025 4869. All rights reserved.": "© 2024–2025 4869。保留所有权利。",
  "🔒 Zero Data Collection": "🔒 零数据收集",
  "Decoy Password": "诱饵密码",
  "Decoy & Recovery": "诱饵与恢复",
  "English": "English",
  "Privacy Policy — 4869": "隐私政策 — 4869",
  "Last updated: January 1, 2025": "最后更新时间：2025 年 1 月 1 日",
  "The short version:": "简短版本：",
  "The current version of 4869 does not collect, transmit, or share personal data. It has no servers, accounts, telemetry, analytics, or implemented network requests. Local vault data and preferences remain on your Mac.": "4869的当前版本不收集、传输或共享个人数据。它没有服务器、帐户、遥测、分析或实施的网络请求。本地保险库数据和偏好设置保留在您的 Mac 上。",
  "1. Overview": "1. 概述",
  "4869 (\"the App\") is a local-only file encryption application for macOS. The current version contains no code that sends information from your computer to an external service.": "4869（“应用程序”）是一款适用于 macOS 的本地文件加密应用程序。当前版本不包含将信息从您的计算机发送到外部服务的代码。",
  "This Privacy Policy describes how the App handles data, including data processed locally on your device and how that data is protected.": "本隐私政策描述了应用程序如何处理数据，包括在您的设备上本地处理的数据以及如何保护该数据。",
  "2. Data We Do Not Collect": "2. 我们不收集的数据",
  "The App explicitly does": "该应用程序明确执行",
  "not": "不是",
  "collect or process any of the following:": "收集或处理以下任何内容：",
  "Personal information:": "个人信息：",
  "No name, email, phone number, or identity is ever requested or stored.": "不会请求或存储任何姓名、电子邮件、电话号码或身份。",
  "Account data:": "账户数据：",
  "The App has no account system. No login, registration, or authentication is required.": "该应用程序没有帐户系统。无需登录、注册或身份验证。",
  "Usage analytics:": "使用情况分析：",
  "No telemetry, crash reports, usage statistics, or behavioral data are collected.": "不会收集遥测、崩溃报告、使用统计或行为数据。",
  "Network data:": "网络数据：",
  "The App makes zero network requests. There are no API endpoints, no servers, and no cloud infrastructure.": "该应用程序的网络请求为零。没有 API 端点、没有服务器、也没有云基础设施。",
  "Advertising data:": "广告数据：",
  "The App contains no advertisements and does not participate in any ad network.": "该应用程序不包含任何广告，也不参与任何广告网络。",
  "Device information:": "设备信息：",
  "No hardware identifiers, MAC addresses, serial numbers, or system profiles are read.": "不会读取硬件标识符、MAC 地址、序列号或系统配置文件。",
  "Location data:": "位置数据：",
  "The App does not access, request, or store any location information.": "该应用程序不会访问、请求或存储任何位置信息。",
  "3. Data Stored on Your Device": "3.您设备上存储的数据",
  "The following data is stored locally on your Mac. None of it is ever transmitted anywhere.": "以下数据存储在您的 Mac 本地。这些信息都不会被传输到任何地方。",
  "3.1 Vault Files": "3.1 库文件",
  "When you encrypt a folder, the App creates encrypted vault data (a  package) at the location of the original folder. This data is protected by your password through scrypt key derivation and AES-256-GCM + ChaCha20-Poly1305 encryption. The App does not retain a copy of your plaintext files or your password after the encryption process completes.": "当您加密文件夹时，应用程序会在原始文件夹的位置创建加密的保险库数据（包）。此数据通过 scrypt 密钥派生和 AES-256-GCM + ChaCha20-Poly1305 加密由您的密码保护。加密过程完成后，该应用程序不会保留您的纯文本文件或密码的副本。",
  "3.2 Post-Quantum Recovery Key (Optional)": "3.2 后量子恢复密钥（可选）",
  "If you enable post-quantum recovery, a recovery key document is generated and offered for you to save to a location of your choosing. The App does not retain this key. If you lose both your password and the recovery key, your data is permanently unrecoverable.": "如果您启用后量子恢复，则会生成恢复密钥文档并供您保存到您选择的位置。该应用程序不保留此密钥。如果您同时丢失密码和恢复密钥，您的数据将永久无法恢复。",
  "3.3 App Preferences": "3.3 应用程序首选项",
  "The App stores a minimal set of preferences using macOS :": "该应用程序使用 macOS 存储最少的首选项集：",
  "Temporary unlock duration preference (1, 5, 15, or 30 minutes).": "临时解锁持续时间首选项（1、5、15 或 30 分钟）。",
  "Path of a folder currently being encrypted (for crash recovery only; cleared immediately after encryption completes).": "当前正在加密的文件夹的路径（仅用于崩溃恢复；加密完成后立即清除）。",
  "These preferences contain no sensitive personal data and are stored only on your device.": "这些偏好设置不包含敏感的个人数据，仅存储在您的设备上。",
  "3.4 Temporary Decryption Cache": "3.4 临时解密缓存",
  "When using the temporary viewing feature, decrypted copies of your files are placed in the system temporary directory with owner-only permissions. The App removes them when the viewing session expires, during orderly App termination, or on the next launch after an interruption. Storage hardware and filesystem behavior may prevent guaranteed physical erasure.": "使用临时查看功能时，文件的解密副本将放置在具有仅限所有者权限的系统临时目录中。当查看会话过期、有序应用程序终止期间或中断后下次启动时，应用程序会删除它们。存储硬件和文件系统行为可能会阻止有保证的物理擦除。",
  "4. How Your Data Is Protected": "4. 如何保护您的数据",
  "The App employs industry-leading cryptographic protection for your data:": "该应用程序对您的数据采用行业领先的加密保护：",
  "scrypt key derivation": "scrypt 密钥派生",
  "(RFC 7914) with N=131,072, r=8, p=1, forcing ~128 MB of RAM per password verification attempt.": "(RFC 7914)，N=131,072，r=8，p=1，每次密码验证尝试强制使用约 128 MB RAM。",
  "Double-layer authenticated encryption": "双层认证加密",
  "using AES-256-GCM (inner) and ChaCha20-Poly1305 (outer) for every file chunk.": "对每个文件块使用 AES-256-GCM（内部）和 ChaCha20-Poly1305（外部）。",
  "HKDF-SHA512": "HKDF-SHA512",
  "for domain-separated sub-key derivation.": "用于域分隔的子密钥派生。",
  "Cryptographically secure random number generation": "加密安全的随机数生成",
  "via .": "通过 。",
  "Core dump protection": "核心转储保护",
  "via  to prevent memory being written to disk.": "通过防止内存被写入磁盘。",
  "Best-effort memory handling": "尽力而为的内存处理",
  "with  zeroing for mutable key buffers and narrow key lifetimes. Copies managed internally by Swift or CryptoKit cannot be guaranteed to be overwritten.": "对可变密钥缓冲区进行归零并缩短密钥生命周期。不能保证由 Swift 或 CryptoKit 内部管理的副本被覆盖。",
  "Secure file deletion": "安全文件删除",
  "with random overwrite, truncation, and unlinking.": "随机覆盖、截断和取消链接。",
  "Cryptographic self-test": "密码自检",
  "on every App launch to verify algorithm integrity.": "在每次应用程序启动时验证算法完整性。",
  "5. Third-Party Services": "5. 第三方服务",
  "The App does": "该应用程序确实",
  "use any third-party services. There are no SDKs, no libraries that make network calls, no analytics platforms, no advertising networks, and no cloud providers involved in the App's operation.": "使用任何第三方服务。没有 SDK、没有进行网络调用的库、没有分析平台、没有广告网络，也没有参与应用程序运行的云提供商。",
  "The App relies solely on Apple's built-in frameworks (, , , , ) which are part of macOS and subject to Apple's own privacy standards.": "该应用程序仅依赖于 Apple 的内置框架 (, , , , )，这些框架是 macOS 的一部分，并遵守 Apple 自己的隐私标准。",
  "6. Children's Privacy": "6. 儿童隐私",
  "The App is not directed at children under the age of 13. The App does not knowingly collect any personal information from anyone, including children. If you believe that a child has provided personal information to the App, please be assured that the App has no means of receiving, storing, or processing such information.": "该应用程序不针对 13 岁以下的儿童。该应用程序不会故意收集任何人（包括儿童）的个人信息。如果您认为儿童向应用程序提供了个人信息，请放心，应用程序无法接收、存储或处理此类信息。",
  "7. Your Rights": "7. 您的权利",
  "Because the App collects no data, the following rights are inherently satisfied:": "由于该应用程序不收集任何数据，因此本质上满足以下权利：",
  "Right to access:": "访问权：",
  "All your data is on your device. You have full access at all times.": "您的所有数据都在您的设备上。您始终拥有完全访问权限。",
  "Right to deletion:": "删除权：",
  "Delete the App and its vault files to remove all data permanently.": "删除应用程序及其保险库文件以永久删除所有数据。",
  "Right to data portability:": "数据可移植权：",
  "Your encrypted vault files are portable and can be moved or copied freely.": "您的加密保险库文件是可移植的，可以自由移动或复制。",
  "Right to opt-out:": "选择退出的权利：",
  "There is nothing to opt out of — no data is collected.": "没有什么可以选择退出——不会收集任何数据。",
  "The App is compliant with the General Data Protection Regulation (GDPR), the California Consumer Privacy Act (CCPA), and all other major privacy regulations by virtue of its zero-data-collection design.": "该应用程序凭借其零数据收集设计，符合《通用数据保护条例》(GDPR)、《加州消费者隐私法案》(CCPA) 和所有其他主要隐私法规。",
  "8. Data Breach Notification": "8. 数据泄露通知",
  "Because the App stores no data on any server and has no network capability, a server-side data breach affecting the App is structurally impossible. If a vulnerability is discovered in the App itself, it will be disclosed on this website and through the App's GitHub repository.": "由于该应用程序没有在任何服务器上存储数据，并且没有网络功能，因此影响该应用程序的服务器端数据泄露在结构上是不可能的。如果应用程序本身发现漏洞，将在本网站上并通过应用程序的 GitHub 存储库进行披露。",
  "9. Changes to This Policy": "9. 本政策的变更",
  "If the App's data practices ever change (for example, if a future version adds optional cloud sync), this Privacy Policy will be updated accordingly and the \"Last updated\" date will reflect the change. You will always be able to find the current version of this policy on this page.": "如果应用程序的数据实践发生变化（例如，如果未来版本添加了可选的云同步），本隐私政策将相应更新，并且“上次更新”日期将反映更改。您始终可以在此页面上找到该政策的当前版本。",
  "10. Contact": "10. 联系方式",
  "If you have questions about this Privacy Policy, please contact:": "如果您对本隐私政策有疑问，请联系：",
  "GitHub:": "GitHub：",
  "github.com/AaronYang47/4869": "github.com/AaronYang47/4869",
  "Support:": "支持：",
  "GitHub Issues": "GitHub 问题",
  "Support Page:": "支持页面：",
  "aaronyang47.github.io/4869/support.html": "aaronyang47.github.io/4869/support.html",
  "Support & Contact — 4869": "支持与联系 — 4869",
  "We're here to help.": "我们随时为您提供帮助。",
  "Questions, concerns, bug reports, or feedback? Reach out through any of the channels below.\n                    We read and respond to every message.": "有问题、疑虑、错误报告或反馈吗？通过以下任何渠道联系我们。\n                    我们阅读并回复每条消息。",
  "For general support, questions, and feedback.": "用于一般支持、问题和反馈。",
  "Open a GitHub issue": "打开 GitHub 问题",
  "For bug reports, feature requests, and source code review.": "用于错误报告、功能请求和源代码审查。",
  "Security Reports": "安全报告",
  "Found a vulnerability? Please report it responsibly.": "发现漏洞？请负责任地举报。",
  "Report privately on GitHub": "在 GitHub 上私下举报",
  "Quick Answers": "快速解答",
  "📖 Frequently Asked Questions": "📖 常见问题",
  "🔒 Privacy Policy": "🔒 隐私政策",
  "📄 Terms of Use": "📄 使用条款",
  "🔐 Security Details": "🔐 安全详情",
  "Send a Message": "发送消息",
  "Fill out the form below and your email client will open with a pre-filled message.": "填写下面的表格，您的电子邮件客户端将打开并显示一条预先填写的消息。",
  "Your Name": "你的名字",
  "Your Email": "您的电子邮件",
  "Message": "信息",
  "Send Message": "发送消息",
  "⚠️ Important Notice About Password Recovery": "⚠️关于密码恢复的重要通知",
  "If you have forgotten your password and did not set up a post-quantum recovery key,": "如果您忘记了密码并且没有设置后量子恢复密钥，",
  "there is nothing we can do to recover your data.": "我们无法恢复您的数据。",
  "This is a fundamental security property of the App — there is no backdoor, no master key,\n                    and no server-side override. If you are in this situation, we sympathize, but mathematics\n                    cannot be bargained with. Please always set up post-quantum recovery and store your\n                    recovery key in a safe, separate location.": "这是应用程序的基本安全属性——没有后门，没有主密钥，\n                    并且没有服务器端覆盖。如果你遇到这种情况，我们表示同情，但是数学\n                    不能讨价还价。请始终设置后量子恢复并存储您的\n                    恢复密钥位于安全、单独的位置。",
  "Typical response time:": "典型响应时间：",
  "24–48 hours": "24–48 小时",
  "·\n                    Languages supported:": "·\n                    支持的语言：",
  "English, 中文": "英语、中文",
  "Terms of Use & Disclaimer — 4869": "使用条款和免责声明 — 4869",
  "By downloading, installing, or using 4869 (\"the App\"), you agree to these Terms of Use. If you do not agree, do not use the App.": "下载、安装或使用4869（“应用程序”）即表示您同意这些使用条款。如果您不同意，请勿使用该应用程序。",
  "1. License": "1. 许可证",
  "Subject to your compliance with these Terms, the developer grants you a limited, non-exclusive, non-transferable, revocable license to download, install, and use the App for your personal, non-commercial or commercial use on macOS devices that you own or control.": "在您遵守这些条款的前提下，开发人员授予您有限的、非独占的、不可转让的、可撤销的许可，以在您拥有或控制的 macOS 设备上下载、安装和使用该应用程序，用于个人、非商业或商业用途。",
  "2. Permitted Use": "2. 允许的用途",
  "You may:": "您可以：",
  "Use the App to encrypt and decrypt folders on your own Mac.": "使用该应用程序加密和解密您自己的 Mac 上的文件夹。",
  "Use the App in a professional or enterprise setting for protecting confidential data.": "在专业或企业环境中使用该应用程序来保护机密数据。",
  "Share information about the App, including screenshots and reviews.": "分享有关该应用程序的信息，包括屏幕截图和评论。",
  "Examine the App's cryptographic design and source code for audit purposes.": "检查应用程序的加密设计和源代码以进行审计。",
  "3. Prohibited Use": "3. 禁止使用",
  "You may": "您可以",
  "Reverse engineer, decompile, or disassemble the App's compiled binary for the purpose of creating derivative works.": "为了创建衍生作品，对应用程序的已编译二进制文件进行逆向工程、反编译或反汇编。",
  "Redistribute, resell, sublicense, or repackage the App without written permission.": "未经书面许可，重新分发、转售、再许可或重新打包应用程序。",
  "Use the App for any unlawful purpose, including but not limited to concealing evidence of a crime.": "将应用程序用于任何非法目的，包括但不限于隐藏犯罪证据。",
  "Remove or alter any copyright notices or attributions within the App.": "删除或更改应用程序内的任何版权声明或归属。",
  "Claim that you authored or own the App.": "声称您创作或拥有该应用程序。",
  "4. Disclaimer of Warranties": "4. 免责声明",
  "IMPORTANT — READ CAREFULLY:": "重要 — 请仔细阅读：",
  "THE APP IS PROVIDED \"AS IS\" AND \"AS AVAILABLE,\" WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.": "该应用程序按“原样”和“可用”提供，不提供任何明示或暗示的保证，包括但不限于适销性、特定用途的适用性和不侵权的保证。",
  "THE DEVELOPER DOES NOT WARRANT THAT:": "开发商不保证：",
  "The App will meet your specific requirements or expectations.": "该应用程序将满足您的特定要求或期望。",
  "The App will operate error-free, uninterrupted, or secure from all threats.": "该应用程序将无差错、不间断地运行或免受所有威胁。",
  "The encryption will be unbreakable under all conceivable future scenarios, including unforeseen advances in cryptanalysis or quantum computing.": "在所有可以想象的未来场景下，包括密码分析或量子计算方面不可预见的进步，加密将是受到保护的。",
  "Your data will always be recoverable, especially if you forget your password and lose your recovery key.": "您的数据始终是可恢复的，尤其是在您忘记密码并丢失恢复密钥的情况下。",
  "Secure file deletion will render data completely unrecoverable on all storage media, including SSDs with wear-leveling or copy-on-write filesystems.": "安全文件删除将使所有存储介质上的数据完全无法恢复，包括具有磨损均衡或写时复制文件系统的 SSD。",
  "You bear all risk of data loss.": "您承担数据丢失的所有风险。",
  "The Developer strongly recommends maintaining an independent backup of any data you encrypt with the App, stored in a secure location separate from your working copies.": "开发人员强烈建议对使用应用程序加密的任何数据进行独立备份，并将其存储在与工作副本分开的安全位置。",
  "5. Limitation of Liability": "5. 责任限制",
  "TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL THE DEVELOPER BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF DATA, PROFITS, OR REVENUE, ARISING OUT OF OR RELATED TO YOUR USE OF OR INABILITY TO USE THE APP, WHETHER BASED ON WARRANTY, CONTRACT, TORT (INCLUDING NEGLIGENCE), OR ANY OTHER LEGAL THEORY, WHETHER OR NOT THE DEVELOPER HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.": "在适用法律允许的最大范围内，在任何情况下，开发者均不对因您使用或无法使用本软件而引起的或与之相关的任何间接、偶然、特殊、后果性或惩罚性损害或任何数据、利润或收入损失承担责任。应用程序，无论基于保证、合同、侵权行为（包括疏忽）或任何其他法律理论，无论开发者是否已被告知发生此类损害的可能性。",
  "Because some jurisdictions do not allow the exclusion or limitation of certain damages, the above limitation may not apply to you to the extent required by applicable law.": "由于某些司法管辖区不允许排除或限制某些损害，因此在适用法律要求的范围内，上述限制可能不适用于您。",
  "6. Your Responsibility": "6. 您的责任",
  "You acknowledge and agree that:": "您承认并同意：",
  "You are solely responsible for remembering your password.": "您全权负责记住您的密码。",
  "The App has no \"forgot password\" mechanism and no backdoor. If you forget your password and did not set up post-quantum recovery, your encrypted data is permanently lost.": "该应用程序没有“忘记密码”机制，也没有后门。如果您忘记密码并且未设置后量子恢复，您的加密数据将永久丢失。",
  "You are solely responsible for safeguarding your recovery key": "您全权负责保护您的恢复密钥",
  "if you enable post-quantum recovery. Anyone who obtains both your  vault file and your recovery key can access your data.": "如果启用后量子恢复。获得您的保险库文件和恢复密钥的任何人都可以访问您的数据。",
  "You are solely responsible for maintaining backups.": "您全权负责维护备份。",
  "If your storage device fails, your encrypted vault may become unrecoverable.": "如果您的存储设备出现故障，您的加密保险库可能无法恢复。",
  "You must comply with all applicable laws": "您必须遵守所有适用的法律",
  "in your jurisdiction regarding encryption, data protection, and privacy.": "在您管辖范围内的加密、数据保护和隐私方面。",
  "You will not hold the Developer responsible": "您不会追究开发商的责任",
  "for any data loss resulting from forgotten passwords, lost recovery keys, device failures, software bugs, or user error.": "由于忘记密码、丢失恢复密钥、设备故障、软件错误或用户错误而导致的任何数据丢失。",
  "7. Export Compliance": "7. 出口合规性",
  "The App incorporates strong encryption technology. You acknowledge that the export, re-export, import, and use of encryption software may be subject to the laws, regulations, and export control restrictions of the United States, the European Union, and other jurisdictions. You are responsible for ensuring compliance with all applicable export control laws and regulations. The App is classified under ECCN 5D002 and may qualify for the mass market encryption exemption under License Exception ENC.": "该应用程序采用了强大的加密技术。您承认加密软件的出口、再出口、进口和使用可能受到美国、欧盟和其他司法管辖区的法律、法规和出口管制限制。您有责任确保遵守所有适用的出口管制法律和法规。该应用程序属于 ECCN 5D002 分类，并且可能有资格获得许可例外 ENC 下的大众市场加密豁免。",
  "8. Privacy": "8. 隐私",
  "The App collects no personal data. See our": "该应用程序不收集任何个人数据。看看我们的",
  "for complete details.": "以获得完整的详细信息。",
  "9. Updates and Changes": "9. 更新和变更",
  "The Developer reserves the right to modify, update, or discontinue the App at any time, with or without notice. Updates may be distributed through the Mac App Store. The Developer is not obligated to provide any ongoing support or maintenance for the App.": "开发者保留随时修改、更新或终止应用程序的权利，无论通知与否。更新可以通过 Mac App Store 分发。开发者没有义务为应用程序提供任何持续的支持或维护。",
  "These Terms may be updated from time to time. Continued use of the App after changes constitutes acceptance of the revised Terms. The \"Last updated\" date will always reflect the most recent revision.": "这些条款可能会不时更新。更改后继续使用该应用程序即表示接受修订后的条款。 “最后更新”日期将始终反映最新版本。",
  "10. Governing Law": "10. 适用法律",
  "These Terms shall be governed by and construed in accordance with the laws of the jurisdiction in which the Developer resides, without regard to its conflict of law provisions. Any disputes arising under these Terms shall be resolved in the courts of that jurisdiction.": "这些条款应受开发者所在司法管辖区的法律管辖并根据其解释，不考虑其法律冲突条款。因这些条款引起的任何争议均应在该管辖区的法院解决。",
  "11. Severability": "11. 可分割性",
  "If any provision of these Terms is held to be unenforceable or invalid, that provision will be limited or eliminated to the minimum extent necessary, and the remaining provisions will remain in full force and effect.": "如果这些条款的任何规定被认为不可执行或无效，则该规定将在必要的最小范围内受到限制或消除，而其余规定将仍然具有完全效力。",
  "12. Entire Agreement": "12. 完整协议",
  "These Terms, together with the Privacy Policy, constitute the entire and exclusive understanding and agreement between you and the Developer regarding the App, and supersede all prior agreements, whether oral or written.": "这些条款与隐私政策一起构成您与开发者之间关于应用程序的完整且排他性的理解和协议，并取代所有先前的协议，无论是口头还是书面的。",
  "13. Open Source Acknowledgments": "13. 开源致谢",
  "The App uses the following technologies:": "该应用程序使用以下技术：",
  "Apple CryptoKit": "苹果加密工具包",
  "— AES-GCM, ChaCha20-Poly1305, HKDF, SHA-256, SHA-512": "— AES-GCM、ChaCha20-Poly1305、HKDF、SHA-256、SHA-512",
  "Apple CommonCrypto": "苹果通用加密货币",
  "— PBKDF2-HMAC-SHA256 (scrypt internals)": "— PBKDF2-HMAC-SHA256（scrypt 内部结构）",
  "— Pure-Swift implementation, validated against RFC test vectors": "— Pure-Swift 实现，根据 RFC 测试向量进行验证",
  "Apple Security Framework": "苹果安全框架",
  "— SecRandomCopyBytes CSPRNG": "— SecRandomCopyBytes CSPRNG",
  "XWing-MLKEM768-X25519": "XWing-MLKEM768-X25519",
  "— Post-quantum hybrid KEM (macOS 26+)": "— 后量子混合 KEM (macOS 26+)",
  "14. Contact": "14. 联系方式",
  "No custom crypto. No proprietary": "不使用未经审查的专有密码算法。"
};
(function () {
  const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);
  const nodes=[]; while(walker.nextNode()) nodes.push(walker.currentNode);
  for(const node of nodes){
    const parent=node.parentElement;
    if(!parent||parent.closest('script, style, pre, code, [data-no-translate]')) continue;
    const key=node.nodeValue.trim(), translated=zhTranslations[key];
    if(!translated) continue;
    node.nodeValue=node.nodeValue.match(/^\s*/)[0]+translated+node.nodeValue.match(/\s*$/)[0];
  }
  document.documentElement.lang='zh-CN';
})();
